apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: tom-skeleton

namespace: default

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- secret.yaml
# ingress.yaml는 Ingress Controller가 있는 경우에만 활성화
# - ingress.yaml

commonLabels:
  app: tom-skeleton
  version: v1

images:
- name: tom-reg.kr.ncr.ntruss.com/tom-skeleton
  newTag: latest

replicas:
- name: tom-skeleton
  count: 2

configMapGenerator:
- name: tom-skeleton-config
  literals:
  - NEXT_PUBLIC_API_BASE_URL=http://localhost:8080
  - NEXT_PUBLIC_API_CAREER_URL=http://localhost:8000

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: Always
  target:
    kind: Deployment
    name: tom-skeleton